version: "3.8"

networks:
  odoo_net:
    driver: overlay
    attachable: true

services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80     # HTTP saja
      - --api.dashboard=true
      - --api.insecure=true               # Dashboard langsung di :8080
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - odoo_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo_db:/var/lib/postgresql/data   # tetap local (aman untuk DB)
    networks:
      - odoo_net
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:7
    command: ["redis-server","--requirepass","redispass"]
    networks:
      - odoo_net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  odoo:
    image: odoo:latest
    depends_on:
      - db
      - redis
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      ODOO_RC: /etc/odoo/odoo.conf
    volumes:
      - /mnt/odoo/config/odoo.conf:/etc/odoo/odoo.conf:ro
      - /mnt/odoo/data:/var/lib/odoo
    networks:
      - odoo_net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=odoo_net"

        # ---- Odoo web (8069) via Traefik ----
        - "traefik.http.routers.odoo-web.rule=PathPrefix(`/`)"
        - "traefik.http.routers.odoo-web.entrypoints=web"
        - "traefik.http.routers.odoo-web.service=odoo-web"
        - "traefik.http.services.odoo-web.loadbalancer.server.port=8069"

        # ---- Longpolling/bus (8072) via Traefik ----
        - "traefik.http.routers.odoo-bus.rule=PathPrefix(`/longpolling`)"
        - "traefik.http.routers.odoo-bus.entrypoints=web"
        - "traefik.http.routers.odoo-bus.service=odoo-bus"
        - "traefik.http.services.odoo-bus.loadbalancer.server.port=8072"

volumes:
  odoo_db:
    driver: local
